.node: &node
  image: node:8
  before_script:
    - npm install
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/

stages:
  - deploy

deploy_develop:
  stage: deploy
  environment:
    name: develop
  <<: *node
  script:
    - npm run web-build
    - npm run deploy
  only:
    - develop

deploy_production:
  stage: deploy
  environment:
    name: production
  <<: *node
  script:
    - npm install -g firebase-tools @angular/cli ionic cordova ngx
    - ionic cordova build browser
    - firebase use --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY --only hosting
  only:
    - master
